### ISSUE TITLE
Hyperlink issue

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app-dev#1]
In dev website in the indexes, in the person "Jacobsen Cornelia" the hyperlink in 'mentioned in:" is not working 
https://auden-musulin-papers.github.io/amp-app-dev/amp_person_163.html

![image](https://user-images.githubusercontent.com/42061592/203564629-3418432b-0fa1-4a0b-ab38-97ca7ce76941.png)

**Comment by linxOD** [comment]
This must be the case for most or all entities: 
* uses ARCHE ID instead of Webapp Url
* must be fixed during denormalize script

**Comment by linxOD** [comment]
fixed
