### ISSUE TITLE
Entities and information

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app-dev#2]
In some entities the information has been successfully transferred from Baserow whereas in some others not:
Example:

![image](https://user-images.githubusercontent.com/42061592/203567936-9b7e4ebf-8c33-44cf-bc7b-1f2d7200bc8f.png)
![image](https://user-images.githubusercontent.com/42061592/203567893-91ff41b4-28c3-4060-9478-3aac3c28f44d.png)

**Comment by linxOD** [comment]
dump entities update resolved the issue
