### ISSUE TITLE
docs 0070, 0071 don't appear on the site

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app-dev#22]
The TEI/XML files 0070, 0071 are not available in both dev website and main site.

However the pictures in docs 0072-0075 are loaded without any problems.

**Comment by linxOD** [comment]
since doc 70, 71 did not exist two months ago they can't be part of it. Just start the github action build and they will be available.

**Comment by linxOD** [comment]
[f8cf9df](https://github.com/Auden-Musulin-Papers/amp-app-dev/commit/f8cf9df1b8e0fa8931390b6d4ded29a0d332fb42)
