### ISSUE TITLE
top right option bar

### ISSUE THREAD

**Issue by demigrigo** [Auden-Musulin-Papers/amp-app-dev#23]
When user tries to go through the next document, the right side scroll bar needs to be all the way to the top in order for the cursor to change into hand; if the the scroll is in the middle (see photo) there is not any hand and no opportunity to change the document from that height.

![image](https://github.com/Auden-Musulin-Papers/amp-app-dev/assets/42061592/580b0ef1-21b9-4962-94fb-ff5df44570cc)

I just noticed that the same holds for all general top right option bar

**Comment by linxOD** [comment]
till you scroll to the top or up the navbar is hidden and sometimes still overlaps the upper area. Not a bug but normal behavior.
